# === Stage 1: Build Binary ===
FROM golang:1.22-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/redirect-server ./cmd/redirect/main.go

# === Stage 2: Runtime ===
FROM alpine:3.19
WORKDIR /app
RUN apk --no-cache add ca-certificates

# Создаем директории для логов и для Unix-сокета
RUN mkdir -p /app/logs /var/run/app

COPY --from=builder /app/redirect-server .

# Объявляем volume для логов и директорию IPC сокета
VOLUME ["/app/logs", "/var/run/app"]

EXPOSE 8081

CMD ["./redirect-server"]