# === Stage 1: Build Frontend ===
FROM node:20-alpine AS frontend-builder
WORKDIR /app/frontend

COPY urlshort-front/package*.json ./
RUN npm ci

COPY urlshort-front/ ./
RUN npm run build

# === Stage 2: Build Backend API ===
FROM golang:1.22-alpine AS backend-builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Копируем фронтенд в папку embed
COPY --from=frontend-builder /app/frontend/dist ./cmd/api/dist

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/api-server ./cmd/api/main.go

# === Stage 3: Minimal Runtime ===
FROM alpine:3.19
WORKDIR /app
RUN apk --no-cache add ca-certificates

COPY --from=backend-builder /app/api-server .

EXPOSE 8080

CMD ["./api-server"]