# === Stage 1: Build Binary ===
FROM golang:1.22-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/stats-server ./cmd/stats/main.go

# === Stage 2: Runtime ===
FROM alpine:3.19
WORKDIR /app
RUN apk --no-cache add ca-certificates

# Создаем директорию под Unix socket
RUN mkdir -p /var/run/app

COPY --from=builder /app/stats-server .

# Общий Volume для доступа к файлу сокета
VOLUME ["/var/run/app"]

EXPOSE 8082

CMD ["./stats-server"]